### ISSUE TITLE
tasks.json version 2.0 causes problem matchers to not work

### ISSUE THREAD

**Issue by niemyjski** [ragnarol/Awesome-Typescript-Problem-Matcher#4] opened 2017-12-04 15:07 UTC
I tried upgrading to version 2.0 of the tasks.json and I'm running into all kinds of issues where there says there is always a problem with webpack when there are no issues. I had to revert back to 0.1.0 but I still have to press f5 twice to debug because the problem matcher has issues detecting the webpack complete messages (v3.9.1). Is anyone else experiencing this?

**Comment by ragnarol** [comment] 2017-12-04 16:37
Hi, haven't tried to update to task 2.0, I'll give it a go and see if I can figure out what's wrong. If you can provide a minimum project that replicates the issue would be of help!

**Comment by niemyjski** [comment] 2017-12-11 17:11
I don't have a project and I haven't been able to narrow it down. Were you able to get it to work?

**Comment by ragnarol** [comment] 2017-12-11 17:28
Hi @niemyjski, I have just tried and seems to be working for me.

Simplest Task.json ever:

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "type": "npm",
            "script": "build",
            "problemMatcher": [
                "$awesometsc", "$awesomets-lint"
            ]
        }
    ]
}
```

Can you check if that one does the trick for you?

My npm build is:
`
"build": "node ./node_modules/webpack/bin/webpack.js -d --display-error-details"`

**Comment by ragnarol** [comment] 2017-12-11 17:39
Just as a side not I am using webpack 3.10.0

If you can provide a minimum example were the issue is reproducible that would be great.

How do the errors look like on your output?

An example of mines:

```
ERROR in ./lookup-index/LookupIndexCtrl.ts
[22, 9]: Missing semicolon

 @ ./ToroApp.ts 10:24-65

ERROR in [at-loader] ./lookup-index/LookupIndexCtrl.ts:22:7
    TS1155: 'const' declarations must be initialized.
```

Those are both a TS Lint and a TS errors. Once fixed they go away in next build. I have tried even fixing the errors outside VSCode with the actual file closed on it, once I build the project again the error goes away too.

**Comment by ragnarol** [comment] 2018-01-10 16:20
I am closing this as it doens't seem to be a problem with the extension

**Closed as completed by ragnarol** 2018-01-10 16:20 UTC
Labels: help wanted
